# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version} Edg/{upstream_browser_version}', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://duckduckgo.com'

# Search engines which can be used via the address bar.  Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` braces.  The following further
# placeholds are defined to configure how special characters in the
# search terms are replaced by safe characters (called 'quoting'):  *
# `{}` and `{semiquoted}` quote everything except slashes; this is the
# most   sensible choice for almost all search engines (for the search
# term   `slash/and&amp` this placeholder expands to `slash/and%26amp`).
# * `{quoted}` quotes all characters (for `slash/and&amp` this
# placeholder   expands to `slash%2Fand%26amp`). * `{unquoted}` quotes
# nothing (for `slash/and&amp` this placeholder   expands to
# `slash/and&amp`). * `{0}` means the same as `{}`, but can be used
# multiple times.  The search engine named `DEFAULT` is used when
# `url.auto_search` is turned on and something else than a URL was
# entered to be opened. Other search engines can be used by prepending
# the search engine name to the search term, e.g. `:open google
# qutebrowser`.
# Type: Dict
c.url.searchengines = {'g': 'https://www.google.ch/search?q={}',
        'DEFAULT': 'https://duckduckgo.com/?q={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://duckduckgo.com'

# Xresources colors
import subprocess
def read_xresources(prefix):
    props = {}
    x = subprocess.run(['xrdb', '-query'], stdout=subprocess.PIPE)
    lines = x.stdout.decode().split('\n')
    for line in filter(lambda l : l.startswith(prefix), lines):
        prop, _, value = line.partition(':\t')
        props[prop] = value
    return props

xresources = read_xresources('*')

color0 = xresources['*.color0']
color1 = xresources['*.color1']
color2 = xresources['*.color2']
color3 = xresources['*.color3']
color4 = xresources['*.color4']
color5 = xresources['*.color5']
color6 = xresources['*.color6']
color7 = xresources['*.color7']
color8 = xresources['*.color8']
color9 = xresources['*.color9']
color10 = xresources['*.color10']
color11 = xresources['*.color11']
color12 = xresources['*.color12']
color13 = xresources['*.color13']
color14 = xresources['*.color14']
color15 = xresources['*.color15']

# set qutebrowser colors

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
c.colors.completion.fg = color7

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = color0

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = color0

# Foreground color of completion widget category headers.
c.colors.completion.category.fg = color14

# Background color of the completion widget category headers.
c.colors.completion.category.bg = color0

# Top border color of the completion widget category headers.
c.colors.completion.category.border.top = color0

# Bottom border color of the completion widget category headers.
c.colors.completion.category.border.bottom = color0

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = color7

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = color8

# Top border color of the selected completion item.
c.colors.completion.item.selected.border.top = color8

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = color8

# Foreground color of the matched text in the selected completion item.
c.colors.completion.item.selected.match.fg = color10

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = color10

# Color of the scrollbar handle in the completion view.
c.colors.completion.scrollbar.fg = color7

# Color of the scrollbar in the completion view.
c.colors.completion.scrollbar.bg = color0

# Background color of disabled items in the context menu.
c.colors.contextmenu.disabled.bg = color3

# Foreground color of disabled items in the context menu.
c.colors.contextmenu.disabled.fg = color8

# Background color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.bg = color0

# Foreground color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.fg =  color7

# Background color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.bg = color8

#Foreground color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.fg = color7

# Background color for the download bar.
c.colors.downloads.bar.bg = color0

# Color gradient start for download text.
c.colors.downloads.start.fg = color0

# Color gradient start for download backgrounds.
c.colors.downloads.start.bg = color11

# Color gradient end for download text.
c.colors.downloads.stop.fg = color0

# Color gradient stop for download backgrounds.
c.colors.downloads.stop.bg = color4

# Foreground color for downloads with errors.
c.colors.downloads.error.fg = color6

# Font color for hints.
c.colors.hints.fg = color0

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
c.colors.hints.bg = color9

# Font color for the matched part of hints.
c.colors.hints.match.fg = color7

# Text color for the keyhint widget.
c.colors.keyhint.fg = color7

# Highlight color for keys to complete the current keychain.
c.colors.keyhint.suffix.fg = color7

# Background color of the keyhint widget.
c.colors.keyhint.bg = color0

# Foreground color of an error message.
c.colors.messages.error.fg = color0

# Background color of an error message.
c.colors.messages.error.bg = color6

# Border color of an error message.
c.colors.messages.error.border = color6

# Foreground color of a warning message.
c.colors.messages.warning.fg = color0

# Background color of a warning message.
c.colors.messages.warning.bg = color10

# Border color of a warning message.
c.colors.messages.warning.border = color10

# Foreground color of an info message.
c.colors.messages.info.fg = color7

# Background color of an info message.
c.colors.messages.info.bg = color0

# Border color of an info message.
c.colors.messages.info.border = color0

# Foreground color for prompts.
c.colors.prompts.fg = color7

# Border used around UI elements in prompts.
c.colors.prompts.border = color0

# Background color for prompts.
c.colors.prompts.bg = color0

# Background color for the selected item in filename prompts.
c.colors.prompts.selected.bg = color8

# Foreground color for the selected item in filename prompts.
c.colors.prompts.selected.fg = color7

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = color10

# Background color of the statusbar.
c.colors.statusbar.normal.bg = color0

# Foreground color of the statusbar in insert mode.
c.colors.statusbar.insert.fg = color0

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = color10

# Foreground color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.fg = color0

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = color5

# Foreground color of the statusbar in private browsing mode.
c.colors.statusbar.private.fg = color0

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = color3

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = color7

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = color0

# Foreground color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.fg = color7

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = color0

# Foreground color of the statusbar in caret mode.
c.colors.statusbar.caret.fg = color0

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = color10

# Foreground color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.fg = color0

# Background color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.bg = color11

# Background color of the progress bar.
c.colors.statusbar.progress.bg = color11

# Default color7 color of the URL in the statusbar.
c.colors.statusbar.url.fg = color7

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = color6

# Foreground color of the URL in the statusbar for hovered links.
c.colors.statusbar.url.hover.fg = color7

# Foreground color of the URL in the statusbar on successful load
# (http).
c.colors.statusbar.url.success.http.fg = color4

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = color10

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = color10

# Background color of the tab bar.
c.colors.tabs.bar.bg = color0

# Color gradient start for the tab indicator.
c.colors.tabs.indicator.start = color11

# Color gradient end for the tab indicator.
c.colors.tabs.indicator.stop = color4

# Color for the tab indicator on errors.
c.colors.tabs.indicator.error = color6

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = color7

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = color0

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = color7

# Background color of unselected even tabs.
c.colors.tabs.even.bg = color0

# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = color0

# Foreground color of pinned unselected even tabs.
c.colors.tabs.pinned.even.fg = color7

# Background color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.bg = color0

# Foreground color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.fg = color7

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = color7

# Foreground color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.fg = color8

# Background color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.bg = color8

# Foreground color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.fg = color7

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = color7

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = color8

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = color7

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = color8

# Background color for webpages if unset (or empty to use the theme's
# color).
# c.colors.webpage.bg = color0

# Render all web contents using a dark theme. Example configurations
# from Chromium's `chrome://flags`:  - "With simple HSL/CIELAB/RGB-based
# inversion": Set   `colors.webpage.darkmode.algorithm` accordingly.  -
# "With selective image inversion": Set
# `colors.webpage.darkmode.policy.images` to `smart`.  - "With selective
# inversion of non-image elements": Set
# `colors.webpage.darkmode.threshold.text` to 150 and
# `colors.webpage.darkmode.threshold.color0` to 205.  - "With
# selective inversion of everything": Combines the two variants   above.
# Type: Bool
c.colors.webpage.darkmode.enabled = False

# Default font size to use. Whenever "default_size" is used in a font
# setting, it's replaced with the size listed here. Valid values are
# either a float value with a "pt" suffix, or an integer value with a
# "px" suffix.
# Type: String
c.fonts.default_size = '12pt'

# Add blocking with host and Braves add blocker
config.set('content.blocking.method', 'both')

# Restore mode of website
config.set('tabs.mode_on_change', 'restore')

# Keybindings
# Tabe-close remap
config.bind('d', 'unbound')
config.bind(',d', 'tab-close')

# Passthrough mode remap
config.bind('<Ctrl-q>', 'mode-enter passthrough')
config.bind('<Ctrl-q>', 'mode-leave', mode='passthrough')
config.unbind('<Ctrl-v>')
config.unbind('<Shift+Escape>', mode='passthrough')

# Bindings for pass
config.bind(',p', 'spawn --userscript qute-pass --dmenu-invocation dmenu')
config.bind(',P', 'spawn --userscript qute-pass --dmenu-invocation dmenu --password-only')

# Bindings for mpv
config.bind(',m', 'spawn mpv {url}')
config.bind(',M', 'hint links spawn mpv {hint-url}')

# Hide statusbar and tabs
config.bind(',b', 'config-cycle statusbar.show always never')
config.bind(',t', 'config-cycle tabs.show always never')
config.bind(',x', 'config-cycle statusbar.show always never;; config-cycle tabs.show always never')

# URL specific settings
config.set('content.images', False, '*://localhost:8888/')

